### ISSUE TITLE
how to apply JSON style to the map

### ISSUE THREAD

**Issue by mohadel92** [gonuit/google_static_maps_flutter#11]
hi,
i am really impressed with this package
but i couldn't apply the json File as i used to do with google maps 
is it possible to load or at least map the values in the json to the package

**Comment by gonuit** [comment]
Hi @mohadel92. 
Sorry for the late reply 😞 
For now, it is not possible, **BUT** it could be possible! It will be nice if you could send me more information about the JSON file that you were using before. Is this related to [this](https://developers.google.com/maps/documentation/javascript/importing_data#data)?

**Comment by mohadel92** [comment]
https://mapstyle.withgoogle.com/
No by using above site you can generate a json style file
That can easily be applied to google flutter maps

**Comment by gonuit** [comment]
@mohadel92, For this purpose you can use [official map styles](https://console.cloud.google.com/google/maps-apis/client-styles). This parameter is fully functional (more info can be found here: #7)

**Comment by mohadel92** [comment]
@gonuit 
i tried so and i provided the mapId to the static map
but it doesn't work

**Comment by gonuit** [comment]
@mohadel92
I tested it and it works correctly for me. Can you share more details? What type of error are you receiving? What doesn't work for you?
