### ISSUE TITLE
[Feature] allow caching map image 

### ISSUE THREAD

**Issue by fvisticot** [gonuit/google_static_maps_flutter#3]
It would be nice to cache the image to:
- display image faster when already displayed
- manage offline conditions

Did you plan to implement this feature or getting access to the image on a callback or from controller ?

**Comment by gonuit** [comment]
Hi @fvisticot!
Its great idea to cache your images as you could get rid of uneccesary google API calls and potentialy pay a little les for it :smiley:!

Basically the main target of this package was to provide simple access to static maps service. So, you are able to generate your map URL in safe and comfortable way (I hope so :smile:). How you will use this generated URL is up to you. Feel free to use already implemented packages to cache your images. For example [CACHED_NETWORK_IMAGE](https://pub.dev/packages/cached_network_image) package, which is great for tasks like that. Example usage can be found  [HERE](https://flutter.dev/docs/cookbook/images/cached-images) .

Let me know if it is what you were looking for 😀! If you have any other questions related to this package, I am here for you :smiley:.

**Comment by fvisticot** [comment]
Tx, it works perfectly with the controller and the cached_network_image plugin !
You can close the "issue"

**Comment by gonuit** [comment]
Great! :smiley:
