### ISSUE TITLE
[Feature] Alloc to draw a circles easily as provided by google_maps_flutter

### ISSUE THREAD

**Issue by fvisticot** [gonuit/google_static_maps_flutter#4]
It seems not trivial to add a circle on a static map (need to play with encoding a path).
It would be very nice that this plugin provides the facility to displays circles as it is done with markers.

**Comment by gonuit** [comment]
Hi @fvisticot!

I want to keep this package as simple as possible therefore it just provides access to Google static maps api.

Google static maps allows you to define and use custom markers. For that purpose you can use `Marker.custom` constructor. Look at the example:

```dart
/// Define marker style with custom icon
Marker.custom(
  anchor: MarkerAnchor.bottom,
  icon: "https://goo.gl/1oTJ9Y",
  locations: [
    Location(-3.1694166, -60.1041517),
  ],
)
```
