### ISSUE TITLE
[Request Feture] add map_id tag

### ISSUE THREAD

**Issue by leossmith** [gonuit/google_static_maps_flutter#7]
There is a new map_id tag which makes it so much easier implementing styles, instead of using the style params. Can you please add it? 

Usage is like: &map_id=a03c202

https://developers.google.com/maps/documentation/maps-static/cloud-based-map-styling

Thank you.

**Comment by gonuit** [comment]
Hi @leossmith, `mapId` argument is available in release number 0.4.3 or 0.5.0 (for null safety).

**Comment by leossmith** [comment]
Awesome, thank you, I will give it a go today.
